
/* ------------------BASE DE DONNEES PJS4------------------ */
/* --------------------Armand Drouineau---------------------- */

CREATE TABLE STOCKAGE(
   idStockage INTEGER NOT NULL AUTO_INCREMENT,
   idCompte INTEGER,
   taille INTEGER,
   dateCreation DATE,
   nombreElements INTEGER
);

CREATE TABLE COMPTE(
   idCompte INTEGER NOT NULL AUTO_INCREMENT,
   typeCompte VARCHAR(8),
   pseudo VARCHAR(16),
   mail VARCHAR(32),
   mdp VARCHAR (16),
   idStockage INTEGER
);

CREATE TABLE ENTITE(
   idEntite INTEGER NOT NULL AUTO_INCREMENT,
   nomEntite VARCHAR(16),
   extension VARCHAR(4),
   dateStockage DATE,
   typeEntite VARCHAR(16),
   visibilite VARCHAR(8),
   public BOOLEAN,
   tailleEntite INTEGER,
   idCompte INTEGER NOT NULL
);

CREATE TABLE REPERTOIRE(
   idEntite INTEGER
);

CREATE TABLE DOCUMENT(
   idEntite INTEGER,
   typeDoc VARCHAR(15)
);

CREATE TABLE PARTAGE(
   idCompte INTEGER,
   idCompte2 INTEGER,
   idEntite INTEGER,
   datePartage DATE
);

CREATE TABLE CONTIENT(
   idEntite INTEGER,
   idEntite2 INTEGER
);

CREATE TABLE GROUPE(
   idGroupe INTEGER,
   numGroupe INTEGER
);

CREATE TABLE COUPLE_GROUPE_COMPTE(
   idCompte INTEGER,
   idGroupe INTEGER
);

CREATE TABLE PUBLIC_DOCUMENTS(
   idEntite INTEGER
);

/* ------------------PRIMARY KEYS DES TABLES------------------ */

ALTER TABLE COMPTE
ADD CONSTRAINT PK_COMPTE PRIMARY KEY(idCompte);

ALTER TABLE STOCKAGE
ADD CONSTRAINT PK_STOCKAGE PRIMARY KEY (idStockage);

ALTER TABLE ENTITE
ADD CONSTRAINT PK_ENTITE PRIMARY KEY(idEntite);

ALTER TABLE REPERTOIRE
ADD CONSTRAINT PK_REPERTOIRE PRIMARY KEY(idEntite);

ALTER TABLE DOCUMENT
ADD CONSTRAINT PK_DOCUMENT PRIMARY KEY(idEntite);

ALTER TABLE PARTAGE
ADD CONSTRAINT PK_PARTAGE PRIMARY KEY(idCompte, idCompte2,idEntite);

ALTER TABLE CONTIENT
ADD CONSTRAINT PK_CONTIENT PRIMARY KEY(idEntite, idEntite2);

ALTER TABLE GROUPE
ADD CONSTRAINT PK_GROUPE PRIMARY KEY(idGroupe);

ALTER TABLE PUBLIC_DOCUMENTS
ADD CONSTRAINT PK_PUBLIC_DOCS PRIMARY KEY(idEntite);

/* ------------------ALTER TABLE DES TABLES------------------ */

ALTER TABLE COMPTE
ADD CONSTRAINT FK_COMPTE FOREIGN KEY(idStockage)REFERENCES STOCKAGE(idStockage),
ADD CONSTRAINT U_MAILCOMPTE UNIQUE(mail);

ALTER TABLE STOCKAGE
ADD CONSTRAINT FK_COMPTE_STOCKAGE FOREIGN KEY (idCompte) REFERENCES COMPTE(idCompte) ON DELETE CASCADE;

ALTER TABLE ENTITE
ADD CONSTRAINT FK_ENTITE FOREIGN KEY(idCompte) REFERENCES COMPTE(idCompte) ON DELETE CASCADE;

ALTER TABLE REPERTOIRE
ADD CONSTRAINT FK_REPERTOIRE FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite) ON DELETE CASCADE;

ALTER TABLE DOCUMENT
ADD CONSTRAINT FK_DOCUMENT FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite) ON DELETE CASCADE;

ALTER TABLE PARTAGE
ADD CONSTRAINT FK_PARTAGE FOREIGN KEY(idCompte) REFERENCES COMPTE(idCompte) ON DELETE CASCADE,
ADD CONSTRAINT FK_PARTAGE_COMPTE FOREIGN KEY(IDCompte2) REFERENCES COMPTE(idCompte),
ADD CONSTRAINT FK_PARTAGE_ENTITE FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite)  ON DELETE CASCADE;

ALTER TABLE CONTIENT
ADD CONSTRAINT FK_CONTIENT_ENTITE FOREIGN KEY(idEntite) REFERENCES Repertoire(idEntite) ON DELETE CASCADE,
ADD CONSTRAINT FK_CONTIENT_ENTITE2 FOREIGN KEY(idEntite2) REFERENCES Repertoire(idEntite);
ALTER TABLE COUPLE_GROUPE_COMPTE
ADD CONSTRAINT FK_idCompte FOREIGN KEY (idCompte) REFERENCES COMPTE(idCompte)  ON DELETE CASCADE,
ADD CONSTRAINT FK_idGroupe FOREIGN KEY (idGroupe) REFERENCES GROUPE(idGroupe);

ALTER TABLE PUBLIC_DOCUMENTS
ADD CONSTRAINT FK_PUBLIC_DOCS FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite) ON DELETE CASCADE;

/* ------------------JEU DE TEST------------------ */

INSERT INTO COMPTE (idCompte, typeCompte, pseudo, mail, mdp, idStockage) VALUES ('client', 'kiki','a@c','1234', 3);
INSERT INTO COMPTE (idCompte, typeCompte, pseudo, mail, mdp, idStockage) VALUES ('admin', 'kiki0','a@0c','123456', 2);
INSERT INTO STOCKAGE (idStockage, idCompte, taille, dateCreation, nombreElements) VALUES(1, 500, CURDATE(), 1);
INSERT INTO ENTITE (idEntite, nomEntite, extension, dateStockage, typeEntite, visibilite, public, tailleEntite, idCompte) VALUES('MonRep', 'rep', CURDATE(), 'repertoire', 'non favori', 0, 50, 1);
INSERT INTO PARTAGE(idCompte, idCompte2, idEntite, datePartage) VALUES(1,2,1,CURDATE());
