

-- PROTOTYPE DE LA BASE DE DONNEES DU PROJET

CREATE TABLE STOCKAGE(
   idStockage INTEGER,
   idCompte INTEGER,
   Taille INTEGER,
   DateCreation DATE,
   NombreElements INTEGER
);

CREATE TABLE COMPTE(
   idCompte INTEGER,
   typeCompte VARCHAR(50),
   nom VARCHAR(50),
   mail VARCHAR(50),
   idStockage INTEGER
);

CREATE TABLE ENTITE(
   idEntite INTEGER,
   dateStockage DATE,
   idCompte INTEGER
);

CREATE TABLE REPERTOIRE(
   idEntite INTEGER
);

CREATE TABLE DOCUMENT(
   idEntite INTEGER
);

CREATE TABLE PARTAGE(
   idCompte INTEGER,
   idCompte2 INTEGER,
   idEntite INTEGER,
   DatePartage DATE
);

CREATE TABLE CONTIENT(
   idEntite INTEGER,
   idEntite2 INTEGER
);


ALTER TABLE COMPTE
ADD CONSTRAINT PK_COMPTE PRIMARY KEY(idCompte);


ALTER TABLE STOCKAGE
ADD CONSTRAINT PK_STOCKAGE PRIMARY KEY (idStockage);


ALTER TABLE ENTITE
ADD CONSTRAINT PK_ENTITE PRIMARY KEY(idEntite);


ALTER TABLE REPERTOIRE
ADD CONSTRAINT PK_REPERTOIRE PRIMARY KEY(idEntite);


ALTER TABLE DOCUMENT
ADD CONSTRAINT PK_DOCUMENT PRIMARY KEY(idEntite);


ALTER TABLE PARTAGE
ADD CONSTRAINT PK_PARTAGE PRIMARY KEY(idCompte, idCompte2,idEntite);


ALTER TABLE CONTIENT
ADD CONSTRAINT PK_CONTIENT PRIMARY KEY(idEntite, idEntite2);


ALTER TABLE COMPTE
ADD CONSTRAINT FK_COMPTE FOREIGN KEY(idStockage)REFERENCES STOCKAGE(idStockage),
ADD CONSTRAINT U_MAILCOMPTE UNIQUE(mail);


ALTER TABLE STOCKAGE
ADD CONSTRAINT FK_COMPTE_STOCKAGE FOREIGN KEY (idCompte) REFERENCES COMPTE(idCompte);


ALTER TABLE ENTITE
ADD CONSTRAINT FK_ENTITE FOREIGN KEY(idCompte) REFERENCES COMPTE(idCompte);


ALTER TABLE REPERTOIRE
ADD CONSTRAINT FK_REPERTOIRE FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite);


ALTER TABLE DOCUMENT
ADD CONSTRAINT FK_DOCUMENT FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite);


ALTER TABLE PARTAGE
ADD CONSTRAINT FK_PARTAGE FOREIGN KEY(idCompte) REFERENCES COMPTE(idCompte),
ADD CONSTRAINT FK_PARTAGE_COMPTE FOREIGN KEY(IDCompte2) REFERENCES COMPTE(idCompte),
ADD CONSTRAINT FK_PARTAGE_ENTITE FOREIGN KEY(idEntite) REFERENCES ENTITE(idEntite);


ALTER TABLE CONTIENT
ADD CONSTRAINT FK_CONTIENT_ENTITE FOREIGN KEY(idEntite) REFERENCES Repertoire(idEntite),
ADD CONSTRAINT FK_CONTIENT_ENTITE2 FOREIGN KEY(idEntite2) REFERENCES Repertoire(idEntite);
